/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package toko_kelontong;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class InputBarang extends javax.swing.JFrame {

    /**
     * Creates new form InputBarang
     */
    public InputBarang() {
        initComponents();
         this.setResizable(false);
         getDataComboBox();
         load_table();
         kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        namabarang = new javax.swing.JTextField();
        hargabeli = new javax.swing.JTextField();
        hargajual = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idbarang = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 60, 60));

        jComboBox1.setBackground(new java.awt.Color(228, 228, 228));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 160, 30));

        namabarang.setBackground(new java.awt.Color(228, 228, 228));
        namabarang.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        namabarang.setBorder(null);
        namabarang.setSelectionColor(new java.awt.Color(228, 228, 228));
        namabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namabarangActionPerformed(evt);
            }
        });
        getContentPane().add(namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 343, 160, 20));

        hargabeli.setBackground(new java.awt.Color(228, 228, 228));
        hargabeli.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        hargabeli.setBorder(null);
        hargabeli.setSelectionColor(new java.awt.Color(228, 228, 228));
        hargabeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargabeliActionPerformed(evt);
            }
        });
        getContentPane().add(hargabeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 367, 160, 20));

        hargajual.setBackground(new java.awt.Color(228, 228, 228));
        hargajual.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        hargajual.setBorder(null);
        hargajual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargajualActionPerformed(evt);
            }
        });
        getContentPane().add(hargajual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 160, 20));

        jumlah.setBackground(new java.awt.Color(228, 228, 228));
        jumlah.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jumlah.setBorder(null);
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 413, 160, 20));

        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 110, 30));

        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 160, 60));

        jButton4.setOpaque(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 160, 50));

        jButton5.setOpaque(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 160, 60));

        jButton6.setOpaque(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 160, 60));

        jButton7.setOpaque(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 160, 50));

        jButton8.setOpaque(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 160, 60));

        jButton9.setOpaque(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setBorderPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 160, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 360, 210));

        jButton10.setOpaque(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setBorderPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 493, 80, 50));

        jButton11.setOpaque(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setBorderPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 493, 70, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/INPUT BARANG.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        idbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbarangActionPerformed(evt);
            }
        });
        getContentPane().add(idbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void load_table(){
    DefaultTableModel model = new DefaultTableModel();
       model.addColumn("No");
       model.addColumn("Id Barang");
       model.addColumn("Nama Barang");
       model.addColumn("Harga Beli");
       model.addColumn("Harga Jual");
       model.addColumn("Jumlah");
     try{
         
         int no = 1;
         String sql = "SELECT * FROM `data_barang`";
         java.sql.Connection conn = (Connection) konektor.configDB();
         java.sql.Statement stm = conn.createStatement();
         java.sql.ResultSet rs = stm.executeQuery(sql);
         while(rs.next()){
             model.addRow(new Object[]{
                 no++,rs.getString(1),rs.getString(3),
                 rs.getString(4),rs.getString(5),
                 rs.getString(6),rs.getString(7)
                 
             });
         }
         jTable1.setModel(model);
     } catch(Exception e){
         
     }
}
private void  kosong(){
    idbarang.enable();
    namabarang.setText(null);
    hargabeli.setText(null);
    hargajual.setText(null);
    hargabeli.setText(null);
    jumlah.setText(null);
    jComboBox1.setSelectedItem(this); 
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
                 new  HalamanUtama().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hargajualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargajualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargajualActionPerformed

    public void getDataComboBox(){
        
        String queryEtalaseItem = "SELECT  * FROM `jenis_etalase`";
        try{
        java.sql.Connection conn =(Connection )konektor.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(queryEtalaseItem);
           java.sql.ResultSet rs = pst.executeQuery(queryEtalaseItem);
           while(rs.next()){
               jComboBox1.addItem(rs.getString("jenis_etalase"));
           }
        }catch(Exception e){
            
        }        
    }
    
    static int posisiIndexBarang(){
            ArrayList<String> datIndex = new ArrayList<>();
         
        try{
            String sqlQuery = "SELECT * FROM `data_barang` ORDER BY `indexNo` DESC";
            java.sql.Connection conn = (Connection) konektor.configDB();
            java.sql.PreparedStatement prs = conn.prepareStatement(sqlQuery);
            java.sql.ResultSet rs = prs.executeQuery();
        
              while(rs.next()){
                  datIndex.add(rs.getString("IndexNo"));
             }
             
        } catch(Exception e){
            e.printStackTrace();
        }
        
        
        return Integer.parseInt(datIndex.get(0));
    }
      static int posisiIndexTransaksi(){
            ArrayList<String> dataIndexTransaksi = new ArrayList<>();
         
        try{
            String sqlQuery = "SELECT * FROM `data_barang` ORDER BY `indexNo` DESC";
            java.sql.Connection conn = (Connection) konektor.configDB();
            java.sql.PreparedStatement prs = conn.prepareStatement(sqlQuery);
            java.sql.ResultSet rs = prs.executeQuery();
        
              while(rs.next()){
                  dataIndexTransaksi.add(rs.getString("IndexNo"));
             }
             
        } catch(Exception e){
            e.printStackTrace();
        }
        
        return Integer.parseInt(dataIndexTransaksi.get(0));
    }
    
       static int getPosisiDataBarang(){
            ArrayList<String> data = new ArrayList<>();
         
        try{
            String sqlQuery = "SELECT * FROM `data_barang` ORDER BY `indexNo` DESC";
            java.sql.Connection conn = (Connection) konektor.configDB();
            java.sql.PreparedStatement prs = conn.prepareStatement(sqlQuery);
            java.sql.ResultSet rs = prs.executeQuery();
        
              while(rs.next()){
                  data.add(rs.getString("idbarang"));
             }
             
        } catch(Exception e){
            e.printStackTrace();
        }
        String teksDataBarang = data.get(0).replaceAll("TB", "");
        
        return Integer.parseInt(teksDataBarang);
    }

    
    static int getPosisiTransaksiAkhir(){
            ArrayList<String> dataTF = new ArrayList<>();
         
        try{
            String sqlQuery = "SELECT * FROM `transaksi_beli` ORDER BY `indexNo` DESC";
            java.sql.Connection conn = (Connection) konektor.configDB();
            java.sql.PreparedStatement prs = conn.prepareStatement(sqlQuery);
            java.sql.ResultSet rs = prs.executeQuery();
        
              while(rs.next()){
                  dataTF.add(rs.getString("id_transaksibeli"));
                  
             }
             
        } catch(Exception e){
            e.printStackTrace();
        }
        String teksTransaksiAkhir =dataTF.get(0).replaceAll("TF", "");
        
        return Integer.parseInt(teksTransaksiAkhir);
    }

     static int c(){
         return 1;
     } 
     int posisiTerakhir = getPosisiTransaksiAkhir();
     int indexDataBarang = posisiIndexBarang() + 1;
     int indexTransaksi = posisiIndexTransaksi() + 1;
     int posisiDataBarang = getPosisiDataBarang() + 1 ;
     int posisiDataTransaksi = getPosisiTransaksiAkhir() + 1;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "Input Data Berhasil");
        load_table();
        try {
String sqlx = "INSERT INTO `data_barang`(`idbarang`,`idetalase`,`namabarang`,`hargabeli`,`hargajual`,`stock` "
        + ",`tanggal`,`indexno` ) VALUES('TB" + posisiDataBarang + "'," +
jComboBox1.getSelectedIndex() +",'"+ namabarang.getText() +"'," + hargabeli.getText()  +
"," + hargajual.getText() +"," +jumlah.getText() + ", NOW(),'" + indexDataBarang +"');" ;
    
String queryInsertTransaksi = "INSERT INTO `transaksi_beli`(`id_transaksibeli`,`idBarang`,`indexno`) VALUES"
        + "('TF" + posisiDataTransaksi + "','TB" + posisiDataBarang +"','" +indexTransaksi+"');"; 

             java.sql.Connection conn = (Connection)konektor.configDB();
             java.sql.PreparedStatement pst1=conn.prepareStatement(sqlx);
            pst1.execute();
             java.sql.Connection con = (Connection) konektor.configDB();
             java.sql.PreparedStatement prc = con.prepareStatement(queryInsertTransaksi);
             prc.execute();             
         indexDataBarang ++;
         indexTransaksi++;
         posisiDataBarang ++;
         posisiDataTransaksi ++;
     } catch (Exception e) {
         JOptionPane.showMessageDialog(this, e.getMessage());            
         
     }
          load_table();
          kosong();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void hargabeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargabeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargabeliActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);
                 new  DataToko().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
this.setVisible(false);
                 new  DetailStock().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
this.setVisible(false);
                 new  Pemasukan().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
this.setVisible(false);
                 new  Penjualan().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.setVisible(false);
                 new  Pengeluaran().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
this.setVisible(false);
                 new  Riwayat().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
this.setVisible(false);
                 new  Kontak().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void namabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namabarangActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
                                    
     int baris = jTable1.rowAtPoint(evt.getPoint());
        if(jTable1.getValueAt(baris, 2) == null){
            namabarang.setText("");
        } else{
            namabarang.setText(jTable1.getValueAt(baris, 2).toString());
        }
        if(jTable1.getValueAt(baris,3) == null){
            hargabeli.setText("");
        } else{
            hargabeli.setText(jTable1.getValueAt(baris,3).toString());
        }        
        if(jTable1.getValueAt(baris, 4) == null){
            hargajual.setText("");
        } else{
            hargajual.setText(jTable1.getValueAt(baris,4).toString());
        }
        if(jTable1.getValueAt(baris, 5) == null){
            jumlah.setText("");
        } else{
            jumlah.setText(jTable1.getValueAt(baris, 5).toString());
        }
        if(jTable1.getValueAt(baris, 1) == null){
            idbarang.setText("");
        } else{
            idbarang.setText(jTable1.getValueAt(baris, 1).toString());
        }
    
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
             try {
           String sql = "UPDATE `data_barang`"
                   + "SET NamaBarang = '"+namabarang.getText()
                   +"',HargaBeli= '"+hargabeli.getText()
                   +"',HargaJual= '"+hargajual.getText()
                   +"',stock= '"+jumlah.getText()
                   +"'WHERE data_barang.idBarang= '"+idbarang.getText()
                   +"'";
           java.sql.Connection conn=(Connection)konektor.configDB();
           java.sql.PreparedStatement pat=conn.prepareStatement(sql);
           pat.execute();
           JOptionPane.showMessageDialog(null, "data berhasil di edit");
       }catch (Exception e){
           JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"
           +e.getMessage());
       }
       load_table();
       kosong();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       try{
        String sql = "DELETE FROM `transaksi_beli` WHERE `idBarang` = '" + idbarang.getText().toString() +"';";
        String sql1 =  "DELETE FROM `data_barang` WHERE `idBarang` = '" + idbarang.getText().toString() +"';";
        java.sql.Connection conn = (Connection) konektor.configDB();
        java.sql.Statement smt_2 = conn.createStatement();
        java.sql.Statement smt_1 = conn.createStatement();
        smt_2.execute(sql);
        smt_1.execute(sql1);
      
        JOptionPane.showMessageDialog(null, "berhasil di hapus");
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void idbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbarangActionPerformed

    }//GEN-LAST:event_idbarangActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargabeli;
    private javax.swing.JTextField hargajual;
    private javax.swing.JTextField idbarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField namabarang;
    // End of variables declaration//GEN-END:variables
}
