/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package toko_kelontong;


import java.sql.Connection;
import java.util.ArrayList;


public class Pemasukan extends javax.swing.JFrame {

    /**
     * Creates new form Pemasukan
     */
    public Pemasukan() {
        initComponents();
         this.setResizable(false);
    }
    public void getTotalHari(){
        String sqlx = "SELECT * FROM  `penjualan` WHERE `idpenjualan`";
    }

    static String getPosisiTerakhirDataBarang(){
        ArrayList<String> data = new ArrayList<>();
        try {
            String sqlQuery = "SELECT * FROM `penjualan` ORDER BY `idpenjualan`";
            java.sql.Connection conn =(Connection)konektor.configDB();
            java.sql.PreparedStatement prs = conn.prepareStatement(sqlQuery);
            java.sql.ResultSet rs = prs.executeQuery();
            
            while(rs.next()) {
                data.add(rs.getString("idpenjualan"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return data.get(0);
    }
    int nPosisi;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_total = new javax.swing.JLabel();
        btn_hari = new javax.swing.JButton();
        btn_bulan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setOpaque(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setBorderPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 160, 50));

        jButton5.setOpaque(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 160, 60));

        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 160, 60));

        jButton6.setOpaque(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 160, 60));

        jButton7.setOpaque(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 160, 60));

        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 160, 60));

        jButton4.setOpaque(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 160, 60));

        jButton8.setOpaque(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 160, 60));

        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 60, 60));

        txt_total.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 160, 40));

        btn_hari.setOpaque(false);
        btn_hari.setContentAreaFilled(false);
        btn_hari.setBorderPainted(false);
        btn_hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hari, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 110, 50));

        btn_bulan.setOpaque(false);
        btn_bulan.setContentAreaFilled(false);
        btn_bulan.setBorderPainted(false);
        btn_bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bulanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pemasukan.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
                 new  HalamanUtama().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
int totalHargaJual;
float hari;
public void mendapatHargaBeliTotal(){
    String gethargabeli = "SELECT SUM(harga * jumlah) AS totalharian FROM `penjualan` "
            + "WHERE DAY(tanggal_transaksi) = DAY(now())";
    try {
        java.sql.Connection conn =(Connection)konektor.configDB();
        java.sql.PreparedStatement prs = conn.prepareStatement(gethargabeli);
        java.sql.ResultSet rs = prs.executeQuery(gethargabeli);
        while(rs.next()) {
            System.out.println(rs.getString("totalHarian"));
           hari = Float.parseFloat(rs.getString("totalharian"));
           
            totalHargaJual = (int) hari;
           
        }
    hitungin obj = new hitungin(totalHargaJual);
    txt_total.setText("Rp " +obj.formatHarga(totalHargaJual));
} catch (Exception e) {
    e.printStackTrace();
}
}
float bulan;
 public void mendapatkanHargaBeliTotalBulan (){
    String queryGetHargaBeli = "SELECT SUM(harga * jumlah) AS totalPengeluaranBulanan FROM `penjualan` "
            + "WHERE MONTH(tanggal_transaksi) = MONTH(now()) ";
    try{ 
    java.sql.Connection conn = (Connection) konektor.configDB();
    java.sql.PreparedStatement prs = conn.prepareStatement(queryGetHargaBeli);
    java.sql.ResultSet rs = prs.executeQuery(queryGetHargaBeli);
    while(rs.next()){
        bulan = Float.parseFloat(rs.getString("totalPengeluaranBulanan"));
        totalHargaJual = (int) bulan;
    }
    hitungin obj = new hitungin(totalHargaJual);
    txt_total.setText("Rp " + obj.formatHarga(totalHargaJual));
    } catch(Exception e){
        e.printStackTrace();
    }
}
    private void btn_bulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bulanActionPerformed
        mendapatkanHargaBeliTotalBulan();
    }//GEN-LAST:event_btn_bulanActionPerformed

    private void btn_hariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hariActionPerformed
        mendapatHargaBeliTotal();
    }//GEN-LAST:event_btn_hariActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.setVisible(false);
        new  DataToko().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        new  InputBarang().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new  DetailStock().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        new  Pengeluaran().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setVisible(false);
        new  Riwayat().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        new  Pemasukan().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        new  Penjualan().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.setVisible(false);
        new  Kontak().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed


   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemasukan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bulan;
    private javax.swing.JButton btn_hari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txt_total;
    // End of variables declaration//GEN-END:variables
}
