/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package toko_kelontong;

import java.sql.Connection;
import java.util.ArrayList;

/**
 *
 * @author lenovo
 */
class hitungin{

   private static int harga;
    public hitungin(int harga){
        this.harga = harga;
    }
    public hitungin(String harga){
        this.harga = Integer.parseInt(harga);
    }
    public hitungin(){

    }
    public  void tampilkanHargaSemuaDataTable(){
        formatHarga(harga);
    }
    public void tampilkanHargaTunggal(){
        formatHarga(harga);
    }

    public static void setHarga(int harga) {
        hitungin.harga = harga;
    }

    public static int sum(int start , int end){
        if(end > start){
            int t = end + sum(start , end - 1);
            System.out.println(t + "-");
            return end + sum(start,end - 1);
        } else{
            return end;
        }
    }
        public String formatHarga(int n){
        ArrayList<Character> characterAngka = new ArrayList<>();

        for(int t = 0;t< String.valueOf(n).length(); t++){
            characterAngka.add(String.valueOf(n).charAt(t));
        }
        if(characterAngka.size() == 4){
            characterAngka.add(1,'.');
        } else if(characterAngka.size()== 5) {
            characterAngka.add(2, '.');
        }else if(characterAngka.size() == 6){
//100.000
            characterAngka.add(3,'.');
        } else if(characterAngka.size() == 7){
            characterAngka.add(1,'.');
            characterAngka.add(5,'.');

        }

        for(int t = 0; t< characterAngka.size(); t++){
 
             
            if(t == 0){
                System.out.print("Rp.");
            }
            System.out.print(characterAngka.get(t));
            if(t == characterAngka.size() - 1){
                System.out.println();
            }
        }
        char ch[] = new char[characterAngka.size()];
        for(int t = 0; t< characterAngka.size(); t++){
            ch[t] = characterAngka.get(t);
        }
        return String.copyValueOf(ch);
    }

}
public class Pengeluaran extends javax.swing.JFrame {

    /**
     * Creates new form Pengeluaran
     */
    public Pengeluaran() {
        initComponents();
         this.setResizable(false);
    }

    public void getTotalHari(){
        String sqlx = "SELECT * FROM `transaksi_beli` WHERE  `id_transaksi`";
    }
    
    static String getPosisiTerakhirDataBarang(){
            ArrayList<String> data = new ArrayList<>();
         
        try{
            String sqlQuery = "SELECT * FROM `data_barang` ORDER BY `idbarang` DESC";
            java.sql.Connection conn = (Connection) konektor.configDB();
            java.sql.PreparedStatement prs = conn.prepareStatement(sqlQuery);
            java.sql.ResultSet rs = prs.executeQuery();
        
              while(rs.next()){
                  data.add(rs.getString("idbarang"));
             }
             
        } catch(Exception e){
            e.printStackTrace();
        }
        return data.get(0);
    }
    int nPosisi;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txt_total = new javax.swing.JLabel();
        btn_hari = new javax.swing.JButton();
        btn_bulan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 70, 70));

        txt_total.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 140, 40));

        btn_hari.setOpaque(false);
        btn_hari.setContentAreaFilled(false);
        btn_hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hari, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 110, 50));

        btn_bulan.setOpaque(false);
        btn_bulan.setContentAreaFilled(false);
        btn_bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bulanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 110, 50));

        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 160, 60));

        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 160, 60));

        jButton4.setOpaque(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 160, 60));

        jButton5.setOpaque(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 170, 60));

        jButton6.setOpaque(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 170, 60));

        jButton7.setOpaque(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 160, 60));

        jButton8.setOpaque(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 160, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pengeluarna.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
                 new  HalamanUtama().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
int totalHargaBeli;
    public void mendapatkanHargaBeliTotal(){
    String queryGetHargaBeli = "SELECT SUM(hargaBeli * stock) AS total_PengeluaranHarian FROM `data_barang` WHERE DAY(tanggal) = DAY(now()) ";
    try{ 
    java.sql.Connection conn = (Connection) konektor.configDB();
    java.sql.PreparedStatement prs = conn.prepareStatement(queryGetHargaBeli);
    java.sql.ResultSet rs = prs.executeQuery(queryGetHargaBeli);
    while(rs.next()){
        totalHargaBeli = (Integer.parseInt(rs.getString("total_PengeluaranHarian")));
    }
 hitungin obj = new hitungin(totalHargaBeli);
    txt_total.setText("Rp " + obj.formatHarga(totalHargaBeli));
    } catch(Exception e){
        e.printStackTrace();
    }
}
    public void mendapatkanHargaBeliTotalBulan (){
    String queryGetHargaBeli = "SELECT SUM(hargaBeli * stock) AS totalPengeluaranBulanan FROM `data_barang` WHERE MONTH(tanggal) = MONTH(now()) ";
    try{ 
    java.sql.Connection conn = (Connection) konektor.configDB();
    java.sql.PreparedStatement prs = conn.prepareStatement(queryGetHargaBeli);
    java.sql.ResultSet rs = prs.executeQuery(queryGetHargaBeli);
    while(rs.next()){
        totalHargaBeli = (Integer.parseInt(rs.getString("totalPengeluaranBulanan")));
    }
    hitungin obj = new hitungin(totalHargaBeli);
    txt_total.setText("Rp " + obj.formatHarga(totalHargaBeli));
    } catch(Exception e){
        e.printStackTrace();
    }
}
    private void btn_hariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hariActionPerformed
 
        mendapatkanHargaBeliTotal();
    }//GEN-LAST:event_btn_hariActionPerformed

    private void btn_bulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bulanActionPerformed
        // TODO add your handling code here:
        mendapatkanHargaBeliTotalBulan();
        
    }//GEN-LAST:event_btn_bulanActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
this.setVisible(false);
                 new  Penjualan().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);
                 new  DataToko().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.setVisible(false);
                 new  DetailStock().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
this.setVisible(false);
                 new  Pemasukan ().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);
                 new  InputBarang().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
this.setVisible(false);
                 new  Riwayat().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
this.setVisible(false);
                 new  Kontak().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengeluaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bulan;
    private javax.swing.JButton btn_hari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txt_total;
    // End of variables declaration//GEN-END:variables
}
